### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by didraro** [petemc89/craXcel-web#1]
Can you help me create even the server to do the work? Becouse the script it is connected to a amazon server and that's disable.

**Comment by petemc89** [comment]
Hi @didraro!

Really sorry but I'm no longer supporting the web version of craXcel.

The python application is still working and well, might I recommend you check that out?

https://github.com/petemc89/craXcel-cli

Will be more than happy to help get you started on that.

Best,
Pete
